### ISSUE TITLE
Mapa Mental Web 3.0

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Elisahadad#1]
[Mapa_Mental_Web 3.0_Elisahadad_Mayte_Leon_de_Jesus.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Elisahadad/files/14671791/Mapa_Mental_Web.3.0_Elisahadad_Mayte_Leon_de_Jesus.pdf)

**Comment by JeroRoque** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
@Elisahadad Falta mas información para el mapa mental...
